spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/gameMatchPk"
    username: root
    password: root
    
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true